// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Project.Data.EntityFramework;

namespace Project.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Project.Data.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Price");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<short>("Stock");

                    b.HasKey("ProductId");

                    b.ToTable("Product");

                    b.HasData(
                        new { ProductId = 1, Price = 7500m, ProductName = "Cep Telefonu", Stock = (short)50 },
                        new { ProductId = 2, Price = 12000m, ProductName = "Bilgisayar", Stock = (short)40 },
                        new { ProductId = 3, Price = 3000m, ProductName = "Tablet", Stock = (short)10 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
